big refactor

diff --git a/AppDir/AppRun b/AppDir/AppRun
--- a/AppDir/AppRun
+++ b/AppDir/AppRun
@@ -1,97 +1,59 @@
-#!/usr/bin/env sh
-CURRENTDIR="$(dirname "$(readlink -f "$0")")"
-UDEVNOTICE='No android udev rules detected, use "--getudev" to install'
-UDEVREPO="https://github.com/M0Rf30/android-udev-rules.git"
-cat /etc/udev/rules.d/*droid.rules >/dev/null 2>&1 && UDEVNOTICE=""
-cat /usr/lib/udev/rules.d/*droid.rules >/dev/null 2>&1 && UDEVNOTICE=""
-BIN="${ARGV0#./}"
-unset ARGV0
-export PATH="$CURRENTDIR/bin:$PATH"
+#!/bin/sh
 
-_get_udev_rules() {
-	if cat /etc/udev/rules.d/*droid.rules >/dev/null 2>&1 \
-		|| cat /usr/lib/udev/rules.d/*droid.rules >/dev/null 2>&1; then
-		echo "ERROR: udev rules are already installed!"
-		echo "Errors persisting with installed udev rules may be due to missing"
-		echo "udev rules for device or lack of permissions from device"
-		exit 1
-	fi
-	if ! command -v git >/dev/null 2>&1; then
-		echo "ERROR: you need git to use this function"
-		exit 1
-	fi
-	if command -v sudo >/dev/null 2>&1; then
-		SUDOCMD="sudo"
-	elif command -v doas >/dev/null 2>&1; then
-		SUDOCMD="doas"
-	else
-		echo "ERROR: You need sudo or doas to use this function"
-		exit 1
-	fi
-	printf '%s' "udev rules installer from $UDEVREPO, run installer? (y/N): "
-	read -r yn
-	if echo "$yn" | grep -i '^y' >/dev/null 2>&1; then
-		tmpudev=".udev_rules_tmp.dir"
-		git clone "$UDEVREPO" "$tmpudev" && cd "$tmpudev" || exit 1
-		chmod +x ./install.sh && "$SUDOCMD" ./install.sh
-		cat /etc/udev/rules.d/*droid.rules >/dev/null 2>&1 || exit 1
-		cd .. && rm -rf "$tmpudev" || exit 1
-		echo "udev rules installed successfully!"
-	else
-		echo "Aborting..."
-		exit 1
-	fi
-}
+set -e
+
+CURRENTDIR="$(cd "${0%/*}" && echo "$PWD")"
+BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
+BIN="${ARGV0:-$0}"
+BIN="${BIN##*/}"
+unset ARGV0
 
 _get_symlinks() {
-	BINDIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
-	links="$(find "$CURRENTDIR"/shared/bin -maxdepth 1 -exec file {} \; \
-		| awk -F":" '/ELF/ {print $1}' | xargs -I {} basename {} 2>/dev/null)"
+	set -- "$CURRENTDIR"/bin/*
 	echo ""
 	echo "This function will make wrapper symlinks in $BINDIR"
-	echo "that will point to $APPIMAGE with the names:"
-	echo "$links" | tr ' ' '\n'
+	echo "that will point to $APPIMAGE, this way when you run that symlink"
+	echo "it automatically launches that binary without extra arguments"
 	echo ""
-	echo "Make sure there are not existing files $BINDIR with those names"
-	printf '\n%s' "Proceed with the symlink creation? (Y/n): "
-	read -r yn
-	if echo "$yn" | grep -i '^n' >/dev/null 2>&1; then
-		echo "Aborting..."
-		exit 1
-	fi
-	mkdir -p "$BINDIR" || exit 1
-	for link in $links; do
-			ln -s "$APPIMAGE" "$BINDIR/$link" 2>/dev/null \
-				&& echo "\"$link\" symlink successfully created in \"$BINDIR\""
+	printf '%s' "Proceed with the symlink creation? (Y/n): "; read -r yn
+	case "$yn" in
+		n*|N*) >&2 echo "Aborting..."; exit 1;;
+	esac
+	mkdir -p "$BINDIR"
+	for link do
+		if [ ! -x "$link" ] || [ ! -f "$link" ]; then
+			continue
+		fi
+		link="${link##*/}"
+		ln -s "$APPIMAGE" "$BINDIR"/"$link" 2>/dev/null \
+		  && echo "'$link' successfully created in '$BINDIR'"
 	done
 }
 
-# logic
-if [ -n "$BIN" ] && [ -e "$CURRENTDIR/bin/$BIN" ]; then
-	"$CURRENTDIR/bin/$BIN" "$@" || echo "$UDEVNOTICE"
-elif [ -n "$1" ] && [ -e "$CURRENTDIR/bin/$1" ]; then
-	option="$1"
-	shift
-	"$CURRENTDIR/bin/$option" "$@" || echo "$UDEVNOTICE"
-else
-	case "$1" in
-	'--getudev')
-		_get_udev_rules
-		;;
-	'--getlinks')
-		_get_symlinks
-		;;
-	*)
-		echo ""
-		echo "USAGE: \"${APPIMAGE##*/} [ARGUMENT]\""
-		echo "EXAMPLE: \"${APPIMAGE##*/} adb shell\" to enter adb shell"
-		echo ""
-		echo "You can also make a symlink to $APPIMAGE named adb"
-		echo "and run the symlink to enter adb without typing ${APPIMAGE##*/}"
-		echo ""
-		echo 'use "--getlinks" if you want to make the symlinks automatically'
-		echo ""
-		exit 1
-		;;
+# additional scripts can be placed in the top level bin dir
+# those with a name that ends up .hook will be executed in teh current shell
+# while those that end with bg.hook will be executed in the background
+for hook in "$CURRENTDIR"/bin/*.hook; do
+	[ -x "$hook" ] || continue
+	case "$hook" in
+		*.bg.hook) >&2 echo "exec bg hook: $hook"; "$hook" &;;
+		*.hook)    >&2 echo "exec hook: $hook";    "$hook"  ;;
 	esac
+done
+
+if [ "$1" = '--getlinks' ]; then
+	_getlinks
+fi
+
+# Check if ARGV0 matches any bundled binary, fallback to $1, then main bin
+if [ -f "$CURRENTDIR"/bin/"$BIN" ]; then
+	exec "$CURRENTDIR"/bin/"$BIN" "$@"
+elif [ -f "$CURRENTDIR"/bin/"$1" ]; then
+	BIN="$1"
+	shift
+	exec "$CURRENTDIR"/bin/"$BIN" "$@"
+else
+	>&2 echo "Using default binary adb..."
+	>&2 echo "Run ${APPIMAGE##*/} --getlinks for more info"
+	exec "$CURRENTDIR"/bin/adb "$@"
 fi
